//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChallengeBlog.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Posts
    {
        public int ID { get; set; }

        [Required]
        [Display(Name ="Ingrese un titulo para el Post")]
        public string Titulo { get; set; }
        [Required]
        [Display(Name = "Escriba el contenido del Post")]
        public string Contenido { get; set; }
        [Required]
        [Display(Name = "Ingrese una imagen para el Post")]
        public byte[] Imagen { get; set; }
        [Required]
        [Display(Name = "Ingrese la categoría del Post")]
        public string Categoria { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    }
}
